TOKEN = '' # токен телеграм бота
bot_password = '' # пароль для входа в бот
host_name = '' # ip адрес БД
user_name = '' # пользователь БД
user_password = '' # пароль к БД
db_name = '' # имя базы
persons_path = '' # папка с пользователями
pickle_path = '' # словарь с пользователями и закодированными фото
rtsp_stream = '' # rtsp поток с камеры
http_stream = '' # http поток с камеры
com_port = '' # com-порт arduino
guest_arr = ['Guest1', 'Guest2', 'Guest3', 'Guest4']